### ISSUE TITLE
typo (?) in page 153 of the third edition

### ISSUE THREAD

**Issue by msadeghpour** [darrenjw/smfsb#1]
Hi,

I am reading your book and found a small typo or error. Please let me know in case I am wrong.

Third edition, page 153:

I believe it should be:
x(1) = T * (1-u^{1/m}) 
rather than
x(1) = T * u^{1/m}. 

Similarly,
x(i) := (T-x(i-1)) * (1- u^{1/(m-i+1)}).

By the way, the book is useful for me; thanks!
Mehdi

**Comment by darrenjw** [comment]
Yes, thanks, I think there is an error here, which also affects the 2nd edition of the book (p.151 in the 2nd ed.). I'll prepare an errata for the 3rd edition before closing this issue.

**Comment by darrenjw** [comment]
I've added this to the errata for 2e, and created an errata for 3e including this issue. The errata is linked from the main readme of the repo. Thanks again.
