### ISSUE TITLE
Code in Figure 9.14 page 269 (third edition)

### ISSUE THREAD

**Issue by msadeghpour** [darrenjw/smfsb#2]
Hi. 

I was running the code in Figure 9.14 in page 269 of the third edition.

The code is the CLE approximation of the 2-D reaction-diffusion Lotka-Volterra predator-prey system.

There are two points that became questions to me:

1- If we run the code until T=10, then the resulting plots do not look like the corresponding ones in Figure 9.13 that are obtained using exact Gillespie simulation. I understand that CLE is an approximation, but the discrepancy looks big. However, if we run until T=6, the results look more similar to the ones in Fig. 9.13.

2- This is a more important question one can have when using CLE approximation I think. When I try using smaller dt in the command

stepLV2D = StepCLE2D(LV, c(0.6,0.6), dt=0.1)

in Figure 9.14, the behavior changes a lot, i.e. the resulting plot in Figure 9.15 is very sensitive to the choice of dt. Even when we make dt bigger this happens. So the question is, is there a mechanism to know what dt value in CLE is better in terms of the approximation of the exact Gillespie simulation? 

Thanks in advance.

**Comment by darrenjw** [comment]
These are both interesting questions, but I'm not sure I have good answers to either.

1. The CLE can be a bad approximation to the exact simulation algorithm even in the non-spatial scenario, and even for the simple LV model. In the spatial case it is even less clear when or whether a CLE approximation will be good.

2. This is a different issue. This is the question of the numerical stability of forward finite difference solutions to highly nonlinear parabolic SPDEs (and, indeed, the existence and stability of solutions to the true SPDE). Again, I'm not sure there are easy answers. For this the referenced text of Lord et al is a good place to start, but I don't think they cover anything as complex as this example, simple as it is.

I'll leave this issue open for a while, in case any readers have additional insight.

**Comment by msadeghpour** [comment]
Thanks @darrenjw
