### ISSUE TITLE
Metropolis-Hastings update in page 312 of the third edition

### ISSUE THREAD

**Issue by msadeghpour** [darrenjw/smfsb#3]
Hi.

The derivation of the Metropolis-Hastings update in page 312 is quite unclear. In particular, in the derivation of A, in the second line, why

\pi(x* | x(0), c) 

and not

\pi(x* | x(0), x(1), c)?

Similarly, why  \pi_A(x* | x(0), c) and q(r*) are used instead of \pi_A(x* | x(0), x(1), c) and q(r*|x(0),x(1),c), respectively? If we consider the latter, going from the second line to the third line, do we still get to use the equality

\pi(...)/ \pi_A(...) = L(...)/ L_A(...) ?

Also I was wondering if there is a reference where this derivation is explained in more detail?

Thanks!

**Comment by darrenjw** [comment]
I do gloss over a few details here, as to treat formally would be too technical for this introductory text. But essentially, x(1) is part of the sample path x*, so it's a bit moot as to whether or not you need to explicitly condition on it. More details are given in my 2008 paper:

Golightly, A., Wilkinson, D. J. (2008) Bayesian inference for nonlinear multivariate diffusion models observed with error, Computational Statistics and Data Analysis, 52(3):1674-1693.

But for the real technical details, see the referenced papers by Roberts and Stramer (2001) and Stramer (2008), for example.
